# Generated by Django 5.0.3 on 2024-03-19 16:31

import airdrops.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(choices=[('latest', 'latest'), ('hottest', 'hottest'), ('potential', 'potential')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Airdrop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, upload_to=airdrops.models.upload_airdrop_to)),
                ('description', models.TextField()),
                ('platform', models.CharField(max_length=50)),
                ('total_value', models.CharField(max_length=50)),
                ('total_supply', models.BigIntegerField()),
                ('estimate_value', models.CharField(max_length=50)),
                ('tokens_per_claim', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('max_participants', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('ticker', models.CharField(max_length=50)),
                ('white_paper', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('discord', models.URLField(blank=True)),
                ('medium', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('coinmarketcap', models.URLField(blank=True)),
                ('coingecko', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('isConfirmed', models.BooleanField(default=False)),
                ('kyc_required', models.BooleanField(default=False)),
                ('mail_required', models.BooleanField(default=False)),
                ('phone_required', models.BooleanField(default=False)),
                ('twitter_required', models.BooleanField(default=False)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('end_date', models.DateTimeField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='airdrops.category')),
            ],
        ),
    ]
