# Generated by Django 5.0.3 on 2024-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airdrop',
            name='video',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='total_supply',
            field=models.CharField(max_length=50),
        ),
    ]
