# Generated by Django 5.0.3 on 2024-03-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airdrops', '0002_airdrop_video_alter_airdrop_total_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airdrop',
            name='end_date',
        ),
    ]
