# Generated by Django 5.0.3 on 2024-03-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrops', '0004_alter_airdrop_estimate_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdrop',
            name='estimate_value',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='max_participants',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='platform',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='ticker',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='tokens_per_claim',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='total_supply',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='total_value',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='value',
            field=models.CharField(blank=True, default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='white_paper',
            field=models.URLField(blank=True),
        ),
    ]
