# Generated by Django 5.0.3 on 2024-03-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrops', '0005_alter_airdrop_estimate_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdrop',
            name='ticker',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
