# Generated by Django 5.0.3 on 2024-03-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrops', '0007_alter_airdrop_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airdrop',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
