# Generated by Django 5.0.3 on 2024-03-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airdrops', '0008_alter_airdrop_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airdrop',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='airdrop',
            name='hotness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airdrop',
            name='max_participants',
            field=models.CharField(blank=True, default='Unlimited', max_length=50),
        ),
    ]
