# Generated by Django 5.0.3 on 2024-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='token',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presale',
            name='quantity',
            field=models.BigIntegerField(),
        ),
    ]
